name: ForuxInvisibility
main: com.exloki.foruxi.ForuxInvisibility
version: 0.0.1
description: An ExLoki custom plugin [1.8]
authors: [Exloki]
website: http://www.exloki.com/

commands:
  invisible:
    description: /<command>